services:
  - type: web
    name: churn-prediction-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: GROQ_API_KEY
        value: "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"
